spring:
  profiles:
    include: prod

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${spring.security.oauth2.client.registration.google.client-id}
            client-secret: ${spring.security.oauth2.client.registration.google.client-secret}
            scope:
              - openid
              - email
              - profile